[package]
name = "basealloc"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
basealloc-sys = { path = "crates/basealloc-sys" }
libc = { workspace = true, optional = true }


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
strip = "symbols"

[workspace]
members = ["crates/basealloc-sys", "ffi"]
resolver = "3"

[workspace.dependencies]
libc = "0.2.176"
basealloc-sys = { path = "crates/basealloc-sys" }
basealloc = { path = "." }
