[package]
name = "basealloc-fixed"
version = "0.1.0"
edition = "2024"

[dependencies]
basealloc-sys = { workspace = true }
basealloc-list = { workspace = true }
basealloc-extent = { workspace = true }